version: "3.7"
services:
  ddclient:
    build: .
    image: homecentr/ddclient:local
    environment:
      CRON_SCHEDULE: "* * * * *"
      DDCLIENT_ARGS: "-verbose -debug"
    volumes:
      - ./example/ddclient.conf.tmp:/config/ddclient.conf
    restart: unless-stopped